apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-bff
  labels:
    app: vcare-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-bff
  template:
    metadata:
      labels:
        app: vcare-bff
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-bff
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-bff:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-bff-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-case-service
  labels:
    app: vcare-case-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-case-service
  template:
    metadata:
      labels:
        app: vcare-case-service
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-case-service
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-case-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-case-service-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-notification-service
  labels:
    app: vcare-notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-notification-service
  template:
    metadata:
      labels:
        app: vcare-notification-service
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-notification-service
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-notification-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-notification-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-ocr-service
  labels:
    app: vcare-ocr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-ocr-service
  template:
    metadata:
      labels:
        app: vcare-ocr-service
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-ocr-service
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-ocr-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-ocr-service-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-thaid-auth-service
  labels:
    app: vcare-thaid-auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-thaid-auth-service
  template:
    metadata:
      labels:
        app: vcare-thaid-auth-service
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-thaid-auth-service
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-thaid-auth-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-thaid-auth-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vcare
  name: vcare-dashboard-service
  labels:
    app: vcare-dashboard-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vcare-dashboard-service
  template:
    metadata:
      labels:
        app: vcare-dashboard-service
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
        - name: vcare-dashboard-service
          image: registry-vs.m-society.go.th/kitsune-cop/vcare-backend/vcare-dashboard-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: vcare-dashboard-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
