"""รหัส master attachment_types — ใช้ร่วมกับ welfare_evidences / file_payment."""

ATTACHMENT_TYPE_FAMILY_MEMBER = 8
ATTACHMENT_TYPE_PDF_037 = 9
ATTACHMENT_TYPE_PDF_038 = 10
ATTACHMENT_TYPE_KTB_CORPORATE = 11
# หลักฐานเบิกจ่ายเงินสด/เช็ค (เทียบ VSmart Relative_file field 3/4/5 — ไม่ใช้ id 3/4/5 ของ Care)
ATTACHMENT_TYPE_PROOF_RECEIVING = 13
ATTACHMENT_TYPE_PROOF_PAYMENT = 14
ATTACHMENT_TYPE_CHECK_EVIDENCE = 15
ATTACHMENT_TYPE_OTHER = 99

CASH_DISBURSEMENT_PROOF_TYPE_IDS = frozenset(
    {
        ATTACHMENT_TYPE_PROOF_RECEIVING,
        ATTACHMENT_TYPE_PROOF_PAYMENT,
        ATTACHMENT_TYPE_CHECK_EVIDENCE,
    }
)
PAYMENT_FILE_ATTACHMENT_TYPE_IDS = frozenset(
    {
        ATTACHMENT_TYPE_PDF_037,
        ATTACHMENT_TYPE_PDF_038,
        *CASH_DISBURSEMENT_PROOF_TYPE_IDS,
    }
)
